### ISSUE TITLE
crashing on tapping with two fingers

### ISSUE THREAD

**Issue by ashoksinghal** [Duna/TV-EPG-Android-Recyclerview#2]
app is crashing when I am trying to touch the window with two fingers. Can you please help in fixing it

**Comment by manjusha221** [comment]
Hi @ashoksinghal ashoksinghal , Im also facing same issue, Did you get any fix on this

**Comment by Duna** [comment]
We know the issue. As is written in the library name the destination is TV
screens. But you can fork and handle easily the second touch.

**Comment by ashoksinghal** [comment]
@manjusha221 I fixed this issue the same way as Duna has commented, here is the solution i followed, just add below check in the start of dispatchTouchEvent(MotionEvent ev) in EpgView

if (ev.getPointerCount() > 1)
            return false;

**Comment by manjusha221** [comment]
Thank you @Duna  and @ashoksinghal  fixed that.
