### ISSUE TITLE
First item of channel / program not clickable 

### ISSUE THREAD

**Issue by AdnanAliShabir** [Duna/TV-EPG-Android-Recyclerview#3]
@Duna  Click on first item of channel/programs not clickable. On click of 2nd item it shows data of the first item.

**Comment by AdnanAliShabir** [comment]
When user click on first item of the channel nothing happened and clicking on second item showing data of first item. clicking on second item behave like just clicking on the first item.

**Comment by Duna** [comment]
Can you do a fix, i will include in the repo.
Also the width of the items os not 100% accurate calculated on various
devices, i will include this too

**Comment by Duna** [comment]
> Can you do a fix, i will include in the repo. Also the width of the items os not 100% accurate calculated on various devices, i will include this too


Fixed the items width in the today's commit, now 100% accurate. Not yet pushed in Maven as a new version

**Comment by Duna** [comment]
Fixed in 1.0.3 Maven Central release
