### ISSUE TITLE
Clicks not working

### ISSUE THREAD

**Issue by Raykud** [Duna/TV-EPG-Android-Recyclerview#4]
so I tried to implement the clicks in your demo as I failed to implementing them in my app and realized they don't work. 
I simply implemented them like this:
<img width="760" alt="Screen Shot 2020-07-27 at 13 43 38" src="https://user-images.githubusercontent.com/4366666/88579263-64a76400-d00f-11ea-91f4-ba37552a842c.png">

and realized they don't work BUT.. if you click while scrolling they do work. So basically they only work when you scroll.

**Comment by Duna** [comment]
The EPG needs to scroll **diagonally**, for that dispatchTouchEvent was implemented. Doing so you cannot simply register for clickListener.  You have to handle dispatchtouch event from top view level.

**Comment by Duna** [comment]
Latest commit offer you a way to handle the click event. This is just an example.
