### ISSUE TITLE
The usage license is missing

### ISSUE THREAD

**Issue by robertesw** [Duna/TV-EPG-Android-Recyclerview#5]
Hello,
The repository of your project has no license attached(e.g. Apache 2.0, etc) so the users does not know under which terms it can be used.
Also, it would be nice if you release an update of the project to the Mavencentral so that includes the license info in the POM xml.

**Comment by Duna** [comment]
Hello,

You have to email me in which project do you use the library after it has been released.
You have to add a link to my lib git repository into your android app ar Open Source License.
The library is free to use even in commercial apps, if your company net revenue is less than $100k/year.
Feel free to submit pull requests if you find some improvements.

If willing to support our development you can contribute by a donation toPayPal for username dunatv@gmail.com - you can find also on GIT repositorythe link.

Regards!

**Comment by robertesw** [comment]
Hello,

I understand.. but even so, it is highly recommended to put a license file into your repository where you specify all the requirements that the users have to fulfill in order to use this library in their projects.
Otherwise, the users will not be aware of the license terms without viewing the current discussion(which may be closed at some point in the future :-d) or without asking you directly, which is not the proper way from my point of view..  :-).

Also, last but not least, the license terms that you've described above may not be sufficient for all the usage scenarios: please have a look on the description of the Apache license version 2.0 in order to understand better what I mean.

Thanks for your feedback!

**Comment by Duna** [comment]
I personally do not know what type of license would be. There is a lot of
reading...

**Comment by Duna** [comment]
The license will be MIT

**Comment by Duna** [comment]
Hello

We updated the license to the MIT and having 1.0.4 version in MavenCentral

Uploading to
https://api.bintray.com/content/dunatv/TV_EPG/tvepg/1.0.4/genericepg/duna/project/tvepg/1.0.4/tvepg-1.0.4-sources.jar.
..
Uploaded to '
https://api.bintray.com/content/dunatv/TV_EPG/tvepg/1.0.4/genericepg/duna/project/tvepg/1.0.4/tvepg-1.0.4-sources.jar
'.
Uploading to
https://api.bintray.com/content/dunatv/TV_EPG/tvepg/1.0.4/genericepg/duna/project/tvepg/1.0.4/tvepg-1.0.4-javadoc.jar.
..
Uploaded to '
https://api.bintray.com/content/dunatv/TV_EPG/tvepg/1.0.4/genericepg/duna/project/tvepg/1.0.4/tvepg-1.0.4-javadoc.jar
'.
Uploading to
https://api.bintray.com/content/dunatv/TV_EPG/tvepg/1.0.4/genericepg/duna/project/tvepg/1.0.4/tvepg-1.0.4.aar.
..
Uploaded to '
https://api.bintray.com/content/dunatv/TV_EPG/tvepg/1.0.4/genericepg/duna/project/tvepg/1.0.4/tvepg-1.0.4.aar
'.
Uploading to
https://api.bintray.com/content/dunatv/TV_EPG/tvepg/1.0.4/genericepg/duna/project/tvepg/1.0.4/tvepg-1.0.4.pom.
..
Uploaded to '
https://api.bintray.com/content/dunatv/TV_EPG/tvepg/1.0.4/genericepg/duna/project/tvepg/1.0.4/tvepg-1.0.4.pom
'.


Regards

**Comment by robertesw** [comment]
Hello,

Almost perfect.. :-D
Please have a look on the following links and update accordingly the description page(i.e. <>Code) of your repository with the new information regarding the license:

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#disclaimer

https://github.com/search?l=Java&q=license:mit&type=repositories

**Comment by Duna** [comment]
Cool, never seen such an option on GitHub. Thanks for sharing!

**Comment by robertesw** [comment]
You're welcome! ;-)

**Comment by Duna** [comment]
Awesome, thanks! Done.
