### ISSUE TITLE
Alignment problem

### ISSUE THREAD

**Issue by DCDBionicman** [Duna/TV-EPG-Android-Recyclerview#8]
After scrolling (every time in my case) on the phones programs doesn't fit with channels by vertical alignment
![изображение](https://user-images.githubusercontent.com/53030657/103767181-622f4880-504a-11eb-81a5-f1e67d9a0238.png)

**Comment by Duna** [comment]
Sometimes, in rare situations, this issue occurs, I confirm it, we need an algorithm to vertically align the RVs
When the implementation is done on TV this issue cannot be reproduced. It needs very fast scroolling.

**Comment by Duna** [comment]
@DCDBionicman you have a pull request, did you manage to find a solution, i'll integrate right-away
