### ISSUE TITLE
Default theme colors aren't used

### ISSUE THREAD

**Issue by DCDBionicman** [Duna/TV-EPG-Android-Recyclerview#9]
If I don't specify background colors in my custom items ( for program, timeline, channel) then they are always white. But they should use default theme colors

**Comment by Duna** [comment]
Since this is a generic EPG you can add any custom VIEW to the RV items. Items are fully customizable without modifying the library. See the embedded example. The Program view item is custom made.

**Comment by DCDBionicman** [comment]
Thanks for your reply. What are the advantages of explicitly indicating white for the recyclerView? I see only a minus, in that the default colors are not applied if I use Material theme and they must be specified explicitly.

**Comment by Duna** [comment]
Correct. You can fork it

**Comment by DCDBionicman** [comment]
Yep, but I thought it will be good for the project.

**Comment by Duna** [comment]
The mai purpose of the library is to demonstrate how efficient is RV in
therms of big data.

**Comment by Duna** [comment]
We have an issue open, can you look at it?

**Comment by DCDBionicman** [comment]
Oh, I see. It like a tech demo of technology and you don't interested to support it as a universal library, am I right?

**Comment by Duna** [comment]
Yes, that is correct.
